[package]
name = "typeset-macro"
description = "The layout! macro: the typeset layout DSL at compile time"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
homepage = "https://docs.rs/typeset-macro/latest/typeset-macro/"
repository = "https://github.com/soren-n/typeset-rs/tree/main/typeset-macro"
documentation = "https://docs.rs/typeset-macro/latest/typeset-macro/"
keywords = ["dsl", "pretty", "printer", "parser", "macro"]
categories.workspace = true
license.workspace = true
readme = "README.md"

[lints]
workspace = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
typeset.workspace = true

[lib]
proc-macro = true
